### ISSUE TITLE
Script spotlight

### ISSUE THREAD

**Issue by joaochris** [5pread/Goethe#1]
Is there a way to create a script to spotlight videos in the zoom? To facilitate with keyboard shortcuts.

**Comment by 5pread** [comment]
The code i was working on's working system was based on image recognition, it's joining class with searching buttons on screen and clicking them, some of tasks were done with keyboard shortcuts. As far as i know there is no keyboard-bind or shortcut for spotlighting people on meeting.

I havent thought much about it but I think spotlighting people can be done with this way;

> Get name of someone who you want to spotlight
> Search the input text (name) on screen and locate this participant
> Once you located it, right mouse button and click '**spotlight participant**' button with image recognition again

It's not seems like efficient way but maybe it would work
